In [76]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.datasets import load_wine
import pandas as pd
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold

In [108]:
import random
random.seed(1)
data=load_iris()


In [78]:
import sys
print(sys.path)

['/Users/kondohdaiki/python_bins/prediction', '/Users/kondohdaiki/anaconda3/lib/python311.zip', '/Users/kondohdaiki/anaconda3/lib/python3.11', '/Users/kondohdaiki/anaconda3/lib/python3.11/lib-dynload', '', '/Users/kondohdaiki/anaconda3/lib/python3.11/site-packages', '/Users/kondohdaiki/anaconda3/lib/python3.11/site-packages/aeosa']


In [109]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [80]:
def kfold_score_RandomForestClassifier(x,y,n_split):
    y=np.reshape(y,-1)
    cv = KFold(n_splits=n_split, random_state=1, shuffle=True)
    prediction_model = RandomForestClassifier(random_state=1)
    scores_list = cross_val_score(prediction_model, x, y, scoring='accuracy', cv=cv, n_jobs=-1)
    
    return scores_list,prediction_model

In [110]:
score_list,model=kfold_score_RandomForestClassifier(data.data,data.target,5)

In [111]:
score_list

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 0.9       ])

In [112]:
x_train,x_test,y_train,y_test=train_test_split(data.data,data.target,random_state=1)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

In [84]:
print(x_train[:3])

[[6.5 2.8 4.6 1.5]
 [6.7 2.5 5.8 1.8]
 [6.8 3.  5.5 2.1]]


In [113]:
y_test
y_pred


array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0])

In [49]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred,labels=[0,1,2])

In [47]:
a=[[13,  0,  0],
   [ 0, 15,  1],
   [ 0,  0,  9]]

In [72]:
np.all(a==cm,keepdims=True)

array([[False]])

In [103]:
data=load_wine()
score_list,model=kfold_score_RandomForestClassifier(data.data,data.target,5)
x_train,x_test,y_train,y_test=train_test_split(data.data,data.target,random_state=1)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
cm=confusion_matrix(y_test, y_pred,labels=[0,1,2])

In [74]:
cm

array([[18,  0,  0],
       [ 1, 16,  0],
       [ 0,  0, 10]])

In [104]:
y_pred

array([2, 1, 0, 1, 0, 2, 1, 0, 2, 1, 0, 0, 1, 0, 1, 1, 2, 0, 1, 0, 0, 1,
       2, 0, 0, 2, 0, 0, 0, 2, 1, 2, 2, 0, 1, 1, 1, 1, 1, 0, 0, 1, 2, 0,
       0])

In [65]:
def print_confusion_matrix(x,y,model,labels):
    x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=1)
    model.fit(x_train,y_train)
    y_pred=model.predict(x_test)
    cm=confusion_matrix(y_test, y_pred,labels=labels)

    return cm

In [63]:
labels=[0,1,2]

In [66]:
print_confusion_matrix(data.data,data.target,model,labels=labels)

array([[18,  0,  0],
       [ 1, 16,  0],
       [ 0,  0, 10]])